name: Build library

on:
  push:

jobs:
  build:
    permissions:
      contents: write
      packages: read

    uses: UMRoboticsTeam/umrt-ci-cd/.github/workflows/ros-build.yaml@build-every-push
    with:
      build_image: ghcr.io/umroboticsteam/umrt-build:babbler
      publish_image: ghcr.io/umroboticsteam/umrt-apt-image:latest
      publish_repo: UMRoboticsTeam/umrt-apt-repo
      push_artifacts: ${{ github.ref_name == github.event.repository.default_branch }}
    secrets:
      APT_SIGNING_PUBKEY: ${{ secrets.APT_SIGNING_PUBKEY }}
      APT_SIGNING_KEY: ${{ secrets.APT_SIGNING_KEY }}
      APT_DEPLOY_KEY: ${{ secrets.APT_DEPLOY_KEY }}
